---
layout: post
title: "[Programming] Java 예외처리"
subtitle: "예외처리 개념, 피자 가게 예외처리"
date: 2021-11-13 11:00:00 +0900
background: '/img/posts/06.jpg'
---

목차  
[1. 예외처리 개념](#예외처리-개념)  
[2. 피자 가게 예외처리](#피자-가게-예외처리)  

# 예외처리 개념

예외처리란?  
- 프로그램이 처리되는 동안 특정한 문제가 일어났을 때 처리를 중단하고 다른 처리를 하는 것
- 예외에 대비하여 프로그램의 비정상 종료를 막고 실행 상태를 유지

예외처리 작성법
```java
try{//무조건 한번 작동, 예외를 잡기 위한 부분
    ...
}catch(Exception e){//예외를 잡게 되면 넘어오는 부분
    ...
}finally{//try든 catch든 무조건 한번 작동
    ...
}
```

# 피자 가게 예외처리
피자를 구매할 때, 피자 가격이 손님이 가진 돈보다 더 많을 때 발생하는 예외를 처리한다.

수정하게 될 메소드
1. 손님의 돈을 받는 메소드 pay
2. 수입 증가 확인 메소드 askPay
3. 주문 받는 메소드 getOrder
4. 레스토랑 운영 메소드 run

수정 프로세스
요약: 피자 가격 > 손님 돈 인 경우, 주문 받는 프로세스를 멈추고 다른 손님 받기

1. pay에서 예외처리를 위해 askPay로 던져주기
2. askPay에서 getOrder로 던져주기
3. run에서 try~catch 문으로 예외 잡아주기

([피자 가게 코드](https://github.com/hyeonalim/study/tree/main/PizzaStore)에서 더 자세히 확인할 수 있다.)

Customer.java
```java
//계산, 손님 거스름돈
    int pay(int price) throws Exception{

        System.out.println("가지고 있는 돈을 입력해주세요.");
        int money = scn.nextInt();

        //예외 만들기
        if(money >= price){
                
            System.out.println(price + "를 내겠습니다.");
            money = money - price;
            System.out.println("남은 돈은 " + money + "입니다.");                            
                
        }else{

            Exception e = new Exception("가지고 있는 돈이 부족합니다.");
            throw e;

        }
        
        return price;

    }
```

메소드명 옆 throws Exception은 예외를 다른 곳에 던져주기 위해 사용한다. 만약 사용하지 않는다면, 아래와 같이 핸들링 에러 메세지가 노출된다.

![errorthrow]({{site.baseurl}}/img/post_sixth/error_throw.jpg){: width="100%" height="100%"}

피자 가격이 손님의 돈보다 더 많으면 else문으로 들어가서 예외 메세지를 만들어준 것을 던져준다.

    Exception e = new Exception("가지고 있는 돈이 부족합니다.");

위 코드는 Exception이라는 클래스에서 아래의 메소드를 통해 괄호 안의 메세지를 가지고 올 수 있게 된다.

참조: Exception 클래스에서 불러오는 메소드

```java
public Exception(java.lang.String message) {...}
```

Casher.java
```java
//주문받기
    Order getOrder(Customer cu) throws Exception{

        System.out.println(cu.name() + "님, 주문하시겠습니까?(Y/N)");

        String order = scn.nextLine();
        scn.nextLine();

        if(order.equals("Y")){

            Order od = new Order(); //주문서 만들기

            //기본 피자 가격 +1000
            int price = makeOrder(od) + 1000;
            
            askPay(cu, price); //price는 위의 1000원을 가져옴

            return od;   
        }else{
            System.out.println("나가시는 문은 왼쪽입니다.");

            return null;
        }
                
    }

    //수입 증가 확인
    void askPay(Customer cu, int price) throws Exception{

        System.out.println("피자의 가격은 " + price + "입니다.");
        income += cu.pay(price);
        System.out.println("수입이 " + price + "증가해서 현재" + income + "가지고 있습니다.");

    }
```

getOrder의 askPay에서 예외처리를 받았기에 다시 던져준다. askPay도 동일하다.

PizzaRestarant.java
```java
//레스토랑 프로세스
    void run(){

        Customer cst = new Customer();
        
        cs.hi(); //인사

        try{
         
            Order od = cs.getOrder(cst); //주문받기
            Pizza pz = ch.makePizza(od); //피자 만들기
            sv.serving(pz, cst);
               
        } catch(Exception e){
            System.out.println("주문을 받는데서 실패했습니다.");
        }

    }
```

try의 getOrder문에서 주문을 받는데에서 실패하여 그 다음 메소드들은 실행하지 않고 바로 catch문으로 들어오게 된다. 또한, pay에서 발생했던 예외를 닫하주는 메소드이기 때문에 메소드 명 우측에 throws Exception은 사용하지 않아도 괜찮다.